# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pt}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["bryanl"]
  s.date = %q{2010-11-10}
  s.default_executable = %q{pt}
  s.description = %q{Easy access to pivotal tracker that allows you to happy at the CLI}
  s.email = %q{bryan@osesm.com}
  s.executables = ["pt"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/pt",
     "lib/pt.rb",
     "lib/pt/card.rb",
     "lib/pt/iteration.rb",
     "lib/pt/summary.rb",
     "pt.gemspec",
     "spec/pt/card_spec.rb",
     "spec/pt/summary_spec.rb",
     "spec/pt_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/bryanl/pt}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Easy access to pivotal tracker}
  s.test_files = [
    "spec/pt/card_spec.rb",
     "spec/pt/summary_spec.rb",
     "spec/pt_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, ["= 1.3.0"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.6.0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<fakeweb>, ["= 1.3.0"])
      s.add_dependency(%q<httparty>, ["~> 0.6.0"])
      s.add_dependency(%q<thor>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<fakeweb>, ["= 1.3.0"])
    s.add_dependency(%q<httparty>, ["~> 0.6.0"])
    s.add_dependency(%q<thor>, [">= 0"])
  end
end

